In [1]:
import numpy as np

In [2]:
X = np.array([[0,0], [0,1], [1,0], [1,1]])
Y = np.array([[0,0,0,1]]).T
X.shape, Y.shape

((4, 2), (4, 1))

In [3]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [8]:
def derivativeSig(x):
    return sig(z)*(1 - sig(z))

In [4]:
# no hidden layer weights
weights = 2* np.random.random((2, 1)) - 1
bias = 2 * np.random.random(1) - 1
weights, bias

(array([[-0.58107472],
        [ 0.91668347]]),
 array([0.84386896]))

In [5]:
# forward propagation without any hidden layer
output0 = X
output = sig(np.dot(output0, weights) + bias)
output

array([[0.69927944],
       [0.85327883],
       [0.56532305],
       [0.76485388]])

In [6]:
# one hidden layer weights
wh = 2* np.random.random((2, 2)) - 1
bh = 2* np.random.random((1, 2)) - 1
wo = 2 * np.random.random((2, 1)) - 1
bo = 2 * np.random.random((1,1)) - 1

In [7]:
# forward propagation with one hidden layer
output0 = X
outputHidden = sig(np.dot(output0, wh) + bh)
output = sig(np.dot(outputHidden, wo) + bo)
output

array([[0.55637266],
       [0.55352803],
       [0.54279445],
       [0.54105423]])